### ISSUE TITLE
Choose DHCP or Static, manually configure IP/Gateway/Mask

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/ESPSerialWiFiManager#6]
Ability to configure DHCP vs Static connections? I.E. prompt for IP, Mask, Gateway on manual config? I think we had talked about this, but I can see people asking for this to be added.

**Comment by adammhaile** [comment]
Yeah... not sure how best to handle this. I didn't want to add it to the
normal configs because most people wouldn't care and it muddles up the
amount of options you have to go through. One thought was to connect as
normal then go back later and do the other manual stuff. But some networks
may fail to connect without that extra config ahead of time. So how about
on all configs... Both Scan and Manual, just a single "Advanced Config?
y/n" that then drops you into a new menu before connecting if yes?

**Comment by haooken** [comment]
I like the idea of having the option on both config types. An idea for the menu naming: "Scan", "Enter SSID", and then under both of those "Manual Config y/n?". The thinking is that the user first has to determine the network to connect to, so make the decision point for that very obvious ("Either I can scan for it or enter the SSID myself)". Then, once the network is specified, they can decide to configure the parameters of that network manually or not. This is mostly a "user experience" thing, but I feel that moving the word "manual" to the part that then goes into typing in the IP/gateway/etc. makes more sense, and for the top level, specifically telling the user "choose this option to enter the SSID" removes any ambiguity.

**Comment by adammhaile** [comment]
Complete.
